### PR TITLE
Updated OpenShift Docs.

### PR DESCRIPTION
**Pull request by robbaronbu**
the deleted files describe older versions of OpenShift and are no longer relavent.

I have updated some more general files.

### CODE REVIEW

**Comment by hgibson1** [comment]
Can you archive instead of delete?Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by robbaronbu** [comment]
Perhaps I am missing something, git already has a copy of the older versions of the document.

I see no value to archiving a copy (that is moving a file to the archive directory) that will contain a mixture of links that are being updated and old links that cannot work with the current version that may or may not have been moved into the archive directory.  It is reasonable if you are dealing a series of files that are not under source control, but once you get things under source control, you already have a consistent older copy already archived in the previous versions.

**Comment by naved001** [comment]
@hgibson1 I think @robbaronbu makes a good argument about not worrying about archiving things anymore since we now have version control here (we also already had it in the wiki, but it was kinda hidden). So I am okay with deleting files.

**Comment by jeremyfreudberg** [comment]
docs.massopen.cloud can also be configured to show other branches and tags (in addition to the tip of master)

**Comment by naved001** [comment]
also @robbaronbu are you sure you wanted to make a branch on the upstream repository rather than your fork?

**Comment by robbaronbu** [comment]
Am using git to store previous versions as consistency between files is guaranteed as opposed to moving deleted files to an archive directory.  Moving the files to an archive directory does not guarantee a consistent set of files.

**Pull request merged**
